### ISSUE TITLE
Update cookie component to work with core branding v5+

### ISSUE THREAD

**Issue by TriangleJuice** [digipolisantwerp/acpaas-ui_web-components#8]
The cookie consent makes use of the [switch component](https://a-ui.github.io/core_branding_scss/#atoms-switch) which uses an updated syntax in core branding v5.0.0. Ideally the Antwerp UI web components also get this (breaking) update.

**Comment by dieter-kunlabora** [comment]
Are there plans to do this update? We would like to use the cookie consent component in an application which is using core branding v5.

Or are there any known workarounds instead? We can 'copy-paste' the old switch component css from core branding v4 and add it to our application as a workaround, but this doesn't sound great

**Comment by TriangleJuice** [comment]
Hey @dieter-kunlabora there is an update coming early 2022, normally in the first weeks of January.
